FROM ubuntu:latest

# Install necessary packages
RUN apt update && apt install -y curl ca-certificates

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x kubectl
RUN mv kubectl /usr/local/bin/

# Verify kubectl installation
RUN kubectl version --client

# Set working directory
WORKDIR /app
