---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-hunter
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
  namespace: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter
        command: ["kube-hunter"]
        args: ["--pod"]
      restartPolicy: Never
  backoffLimit: 4