---
name: "Bump CIVO marketplace cert-manager version"
pipelineid: certmanager

sources:
  app:
    kind: githubrelease
    name: Get latest cert-manager version
    spec:
      owner: cert-manager
      repository: cert-manager
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
      versionfilter:
        # The cert-manager maintains multiple release line and we want to be sure to pick
        # the latest one based on semantic versioning rules and not the latest release.
        kind: semver

targets:
  manifest:
    kind: yaml
    name: Update cert-manager/manifest.yaml
    scmid: kubernetes-marketplace
    spec:
      file: cert-manager/manifest.yaml
      key: version
    sourceid: app

  install:
    kind: file
    name: Update cert-manager/install.sh
    scmid: kubernetes-marketplace
    disablesourceinput: true
    spec:
      file: cert-manager/install.sh
      matchpattern: '/download/(v{0,1})(\d*.\d*.\d*)/'
      replacepattern: '/download/{{ source "app" }}/'

# Define git repository configuration to know where to push changes
# Values are templated and provided via the values.yaml so we can easily
# adapt to the repository owner.
scms:
  kubernetes-marketplace:
    kind: "github"
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      branch: "{{ .github.branch }}"
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'

actions:  
  kubernetes-marketplace:
    kind: "github/pullrequest"
    scmid: kubernetes-marketplace
    title: 'Bump Cert-manager Helm chart to {{ source "app" }}'
    spec:
      usetitleforautomerge: true
      mergemethod: squash
      labels:
        - enhancement 
