apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iomete-operator
    control-plane: controller-manager
  name: iomete-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iomete-operator
  name: iomete-operator-controller-manager
  namespace: iomete-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iomete-operator
  name: iomete-operator-leader-election-role
  namespace: iomete-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iomete-operator
  name: iomete-operator-iometedataplaneenterprise-admin-role
rules:
- apiGroups:
  - charts.iomete.com
  resources:
  - iometedataplaneenterprises
  verbs:
  - '*'
- apiGroups:
  - charts.iomete.com
  resources:
  - iometedataplaneenterprises/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iomete-operator
  name: iomete-operator-iometedataplaneenterprise-editor-role
rules:
- apiGroups:
  - charts.iomete.com
  resources:
  - iometedataplaneenterprises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.iomete.com
  resources:
  - iometedataplaneenterprises/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iomete-operator
  name: iomete-operator-iometedataplaneenterprise-viewer-role
rules:
- apiGroups:
  - charts.iomete.com
  resources:
  - iometedataplaneenterprises
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.iomete.com
  resources:
  - iometedataplaneenterprises/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iomete-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - charts.iomete.com
  resources:
  - iometedataplaneenterprises
  - iometedataplaneenterprises/status
  - iometedataplaneenterprises/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - scheduledsparkapplications
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iomete-operator-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iomete-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iomete-operator
  name: iomete-operator-leader-election-rolebinding
  namespace: iomete-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iomete-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: iomete-operator-controller-manager
  namespace: iomete-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iomete-operator
  name: iomete-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iomete-operator-manager-role
subjects:
- kind: ServiceAccount
  name: iomete-operator-controller-manager
  namespace: iomete-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iomete-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iomete-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: iomete-operator-controller-manager
  namespace: iomete-operator-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iomete-operator
    control-plane: controller-manager
  name: iomete-operator-controller-manager-metrics-service
  namespace: iomete-operator-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: iomete-operator
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iomete-operator
    control-plane: controller-manager
  name: iomete-operator-controller-manager
  namespace: iomete-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iomete-operator
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: iomete-operator
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-require-rbac
        - --metrics-secure
        - --metrics-bind-address=:8443
        - --leader-elect
        - --leader-election-id=iomete-operator
        - --health-probe-bind-address=:8081
        image: iomete.azurecr.io/iomete/iomete-operator:v0.0.7
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports: []
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts: []
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: iomete-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes: []
