apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: tensorboard-controller
    kustomize.component: tensorboard-controller
  name: tensorboard-controller-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
