apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: tensorboards-web-app
    kustomize.component: tensorboards-web-app
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: 'true'
  name: tensorboards-web-app-kubeflow-tensorboard-ui-view
rules:
- apiGroups:
  - tensorboard.kubeflow.org
  resources:
  - tensorboards
  - tensorboards/finalizers
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - poddefaults
  verbs:
  - get
  - list
  - watch
