apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: 'true'
  name: kubeflow-training-view
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  - tfjobs
  - pytorchjobs
  - mxjobs
  - xgboostjobs
  - paddlejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs/status
  - tfjobs/status
  - pytorchjobs/status
  - mxjobs/status
  - xgboostjobs/status
  - paddlejobs/status
  verbs:
  - get
