apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.8.1
    eventing.knative.dev/release: v1.8.1
    kustomize.component: knative
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: 'true'
  name: knative-eventing-namespaced-edit
rules:
- apiGroups:
  - eventing.knative.dev
  - messaging.knative.dev
  - sources.knative.dev
  - flows.knative.dev
  - bindings.knative.dev
  resources:
  - '*'
  verbs:
  - create
  - update
  - patch
  - delete
