apiVersion: v1
data:
  default-br-config: "clusterDefault:\n  brokerClass: MTChannelBasedBroker\n  apiVersion:\
    \ v1\n  kind: ConfigMap\n  name: config-br-default-channel\n  namespace: knative-eventing\n\
    \  delivery:\n    retry: 10\n    backoffPolicy: exponential\n    backoffDelay:\
    \ PT0.2S\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.8.1
    eventing.knative.dev/release: v1.8.1
    kustomize.component: knative
  name: config-br-defaults
  namespace: knative-eventing
