apiVersion: v1
data:
  mesh: "accessLogFile: /dev/stdout\ndefaultConfig:\n  discoveryAddress: istiod.istio-system.svc:15012\n\
    \  proxyMetadata: {}\n  tracing: {}\nenablePrometheusMerge: true\nrootNamespace:\
    \ istio-system\ntcpKeepalive:\n  interval: 5s\n  probes: 3\n  time: 10s\ntrustDomain:\
    \ cluster.local"
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  labels:
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istio
  name: istio
  namespace: istio-system
