apiVersion: v1
data:
  channel-template-spec: 'apiVersion: messaging.knative.dev/v1

    kind: InMemoryChannel

    '
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.8.1
    eventing.knative.dev/release: v1.8.1
    kustomize.component: knative
  name: config-br-default-channel
  namespace: knative-eventing
