apiVersion: v1
data:
  ADMIN: ''
  USERID_HEADER: kubeflow-userid
  USERID_PREFIX: ''
  WORKLOAD_IDENTITY: ''
kind: ConfigMap
metadata:
  labels:
    kustomize.component: profiles
  name: profiles-config-46c7tgh6fd
  namespace: kubeflow
