apiVersion: v1
data:
  artifactRepository: "archiveLogs: true\ns3:\n  endpoint: \"minio-service.kubeflow:9000\"\
    \n  bucket: \"mlpipeline\"\n  # keyFormat is a format pattern to define how artifacts\
    \ will be organized in a bucket.\n  # It can reference workflow metadata variables\
    \ such as workflow.namespace, workflow.name,\n  # pod.name. Can also use strftime\
    \ formating of workflow.creationTimestamp so that workflow\n  # artifacts can\
    \ be organized by date. If omitted, will use `{{workflow.name}}/{{pod.name}}`,\n\
    \  # which has potential for have collisions, because names do not guarantee they\
    \ are unique\n  # over the lifetime of the cluster.\n  # Refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/.\n\
    \  #\n  # The following format looks like:\n  # artifacts/my-workflow-abc123/2018/08/23/my-workflow-abc123-1234567890\n\
    \  # Adding date into the path greatly reduces the chance of {{pod.name}} collision.\n\
    \  keyFormat: \"artifacts/{{workflow.name}}/{{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{pod.name}}\"\
    \n  # insecure will disable TLS. Primarily used for minio installs not configured\
    \ with TLS\n  insecure: true\n  accessKeySecret:\n    name: mlpipeline-minio-artifact\n\
    \    key: accesskey\n  secretKeySecret:\n    name: mlpipeline-minio-artifact\n\
    \    key: secretkey\n"
  containerRuntimeExecutor: emissary
  executor: "imagePullPolicy: IfNotPresent\nresources:\n  requests:\n    cpu: 0.01\n\
    \    memory: 32Mi\n  limits:\n    cpu: 0.5\n    memory: 512Mi\n"
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller-configmap
  namespace: kubeflow
