apiVersion: v1
data:
  _example: '################################

    #                              #

    #    EXAMPLE CONFIGURATION     #

    #                              #

    ################################

    # This block is not actually functional configuration,

    # but serves to illustrate the available configuration

    # options and document them in a way that is accessible

    # to users that `kubectl edit` this config map.

    #

    # These sample configuration options may be copied out of

    # this example block and unindented to be in the data block

    # to actually change the configuration.


    # namespace-selector specifies a LabelSelector which

    # determines which namespaces the Sugar Controller should operate upon

    # Use an empty value to disable the feature (this is the default):

    namespace-selector: ""


    # Use an empty object as a string to enable for all namespaces

    namespace-selector: "{}"


    # trigger-selector specifies a LabelSelector which

    # determines which triggers the Sugar Controller should operate upon

    # Use an empty value to disable the feature (this is the default):

    trigger-selector: ""


    # Use an empty object as string to enable for all triggers

    trigger-selector: "{}"

    '
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: 62dfac6f
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.8.1
    eventing.knative.dev/release: v1.8.1
    kustomize.component: knative
  name: config-sugar
  namespace: knative-eventing
