apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
  labels:
    app: training-operator
  name: training-operator
  namespace: kubeflow
spec:
  ports:
  - name: monitoring-port
    port: 8080
    targetPort: 8080
  selector:
    control-plane: kubeflow-training-operator
  type: ClusterIP
