---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: pyroscope
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pyroscope-server
  labels:
    app.kubernetes.io/name: pyroscope-server
    app.kubernetes.io/instance: pyroscope-server
    app.kubernetes.io/version: "0.2.5"
  namespace: pyroscope
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-server
  labels:
    app.kubernetes.io/name: pyroscope-server
    app.kubernetes.io/instance: pyroscope-server
    app.kubernetes.io/version: "0.2.5"
  namespace: pyroscope
data:
  config.yaml: |
    {}
---
apiVersion: v1
kind: Service
metadata:
  name: pyroscope-server
  labels:
    app.kubernetes.io/name: pyroscope-server
    app.kubernetes.io/instance: pyroscope-server
    app.kubernetes.io/version: "0.2.5"
  namespace: pyroscope
spec:
  type: ClusterIP
  ports:
    - port: 4040
      targetPort: api
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pyroscope-server
    app.kubernetes.io/instance: pyroscope-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: pyroscope-server
    app.kubernetes.io/name: pyroscope-server
    app.kubernetes.io/version: "0.2.5"
  name: pyroscope-server
  namespace: pyroscope
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: pyroscope-server
      app.kubernetes.io/name: pyroscope-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pyroscope-server
        app.kubernetes.io/name: pyroscope-server
        app.kubernetes.io/version: "0.2.5"
    spec:
      serviceAccountName: pyroscope-server
      securityContext:
        fsGroup: 101
      containers:
        - name: pyroscope
          args:
            - "server"
            - "-config"
            - "/tmp/config.yaml"
          securityContext:
            {}
          image: "pyroscope/pyroscope:0.2.5"
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 4040
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 4040
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 4040
          resources:
            {}
          volumeMounts:
            - name: config
              mountPath: /tmp/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: pyroscope-server
